// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKb8IxP7zqO8FLjistbT6fQufoFW3McU',
    appId: '1:108131815177:web:c0ab32ac96c86442754dd8',
    messagingSenderId: '108131815177',
    projectId: 'deep-linking-7c320',
    authDomain: 'deep-linking-7c320.firebaseapp.com',
    storageBucket: 'deep-linking-7c320.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGUg0l9Yr-wRLkTrcOcWUoNUNC3K4VL8',
    appId: '1:108131815177:android:ca5b30d6fc0070eb754dd8',
    messagingSenderId: '108131815177',
    projectId: 'deep-linking-7c320',
    storageBucket: 'deep-linking-7c320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaQYI8sbjgA8sXcTTVfossv3At3TmPXc',
    appId: '1:108131815177:ios:373146746d2de6dd754dd8',
    messagingSenderId: '108131815177',
    projectId: 'deep-linking-7c320',
    storageBucket: 'deep-linking-7c320.appspot.com',
    iosClientId: '108131815177-ihnv073q33vtck9bon5sn3ktniaokivn.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaQYI8sbjgA8sXcTTVfossv3At3TmPXc',
    appId: '1:108131815177:ios:2a908399d85f76b6754dd8',
    messagingSenderId: '108131815177',
    projectId: 'deep-linking-7c320',
    storageBucket: 'deep-linking-7c320.appspot.com',
    iosClientId: '108131815177-13pc5d9vn8sas78ct979gsjicp432qur.apps.googleusercontent.com',
    iosBundleId: 'deep.linking.mac',
  );
}
